### ISSUE TITLE
Missing docstrings in sudoku.py

### ISSUE THREAD

**Issue by ejyager00** [zlee1/SudokuSolver#1]
[sudoku.py](https://github.com/zlee1/SudokuSolver/blob/master/sudoku.py) does not have any docstrings per [PEP 8](https://www.python.org/dev/peps/pep-0008/)

**Comment by ejyager00** [comment]
Also per [PEP 257](https://www.python.org/dev/peps/pep-0257/)

**Comment by zlee1** [comment]
Docstrings added.
